project:
  type: website
  output-dir: docs

website:
  title: "St. Michaels Cemetery"
  navbar:
    search: false
    left:
      - text: "Map"
        file: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

