project:
  type: website

website:
  title: "St. Michaels Cemetery"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

